name: EXIF EXporter

on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install exiftool
        run: sudo apt-get install exiftool
      - name: Run ExifTool
        run: |
          find . -type f \( -iname "*.JPG" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.tiff" -o -iname "*.webp" \) > godendi.txt
          xargs -d '\n' -a godendi.txt \
            exiftool -json -r $(paste -sd ' ' my_entries.txt) \
            | jq 'map({(.SourceFile | sub("^./"; "")): .}) | add' \
            > EXIFDATA.json
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: vincenzogoogle
          author_email: checazzoguardibot@gmail.com
          message: "${{ github.event.head_commit.message }} (EXIF blob updated)"
          add: EXIFDATA.json
          push: true