name: EXIF EXporter

on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install exiftool
        run: sudo apt-get install exiftool
      - name: Get changëd
        id: changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # List files added/modified in this push
          gh api repos/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }} --jq '.files[].filename' | grep -Ei '\.(JPG|jpg|jpeg|tiff|webp)$' > godendi.txt
          if [ ! -s EXIFDATA.json ]; then
            find photos/ -type f \( -iname "*.JPG" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.tiff" -o -iname "*.webp" \) > godendi.txt
            echo '{}' > EXIFDATA.json
          else
            cp EXIFDATA.json exifdata.old.json
          fi
      - name: Run ExifTool
        run: |
          xargs -d '\n' -a godendi.txt exiftool -json -r $(paste -sd ' ' my_entries.txt) | jq 'map({(.SourceFile | sub("^"; "")): .}) | add' > changed.json
      - name: Write to JSON
        run: jq -s '.[0] * .[1]' exifdata.old.json changed.json > EXIFDATA.json
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: vincenzogoogle
          author_email: checazzoguardibot@gmail.com
          message: "${{ github.event.head_commit.message }} (EXIF blob updated)"
          add: EXIFDATA.json
          push: true